### ISSUE TITLE
bug: Mock data export csv file error

### ISSUE THREAD

**Issue by Hypoxia-zhangmingmin** [Caojiahao-Coder/gpt_next#22]
There is a problem with data simulation exporting csv files in AI tools
![1700567511028](https://github.com/Caojiahao-Coder/gpt_next/assets/55157371/9b77cbb4-f482-44d9-bd22-475f50548ef1)

![1700567592063](https://github.com/Caojiahao-Coder/gpt_next/assets/55157371/53cd57c4-7f7e-44df-a6e4-3b850b7ae27d)

**Comment by Caojiahao-Coder** [comment]
Thanks for the feedback, I think I know what the problem is and I'll fix it as soon as I can.

**Comment by Caojiahao-Coder** [comment]
### This issue has been resolved.
#23 
https://github.com/Caojiahao-Coder/gpt_next/releases/tag/v1.3.7-2
<hr/>

<strong>Thanks again for your use and feedback.</strong>
