### ISSUE TITLE
Sorry, failed to generate image. Please try again later.

### ISSUE THREAD

**Issue by ikexue** [Caojiahao-Coder/gpt_next#24]
when i used Draw Image Mode，there is a mistake “Sorry, failed to generate image. Please try again later.”

**Comment by Caojiahao-Coder** [comment]
Thank you for your feedback.

But in my tests, the software works fine. Please provide more information, such as: model、your requirements.

<hr/>

![image](https://github.com/Caojiahao-Coder/gpt_next/assets/68038353/c6d127e3-2fee-4c57-9e57-66e88fd40912)

**Comment by Caojiahao-Coder** [comment]
Due to the lack of response from you for a long time, I have decided to close this issue for now. 😶‍🌫️
