### ISSUE TITLE
How to use prompts?

### ISSUE THREAD

**Issue by socialmedialabs** [Caojiahao-Coder/gpt_next#27]
Maybe I'm missing something obvious, but I can't seem to figure out how to 'apply' a custom prompt to a chat. Any help would be greatly appreciated.

**Comment by Caojiahao-Coder** [comment]
**Thank you for your use! Maybe you can use Prompts like this**

1. Create a Prompt
2. Enter / in the input box
3. Click prompt

<hr/>

![image](https://github.com/Caojiahao-Coder/gpt_next/assets/68038353/c8517801-6219-42c4-bb52-bbf207648274)

<hr/>

![image](https://github.com/Caojiahao-Coder/gpt_next/assets/68038353/bcd93f6b-ce3f-49ff-a29c-74822b08f15a)
